print('='*10+'Calculadora basiva'+'='*10)
valor1 = float(input('Digite o primeiro numero da operação: '))
valor2 = float(input('Digite o segundo numero da operação: '))
print('='*30)
print('Soma: {}'.format(valor1+valor2))
print('Subtração: {}'.format(valor1-valor2))
print('Multiplicação: {}'.format(valor1*valor2))
print('Divisão: {}'.format(valor1/valor2))
print('='*30)
print('Procurem sobre as outras operações!')
